# Generated by Django 3.2 on 2021-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='feedback',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
