# Generated by Django 3.2 on 2021-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_auto_20210602_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
