# Generated by Django 3.2 on 2021-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
