# Generated by Django 3.2 on 2021-06-04 16:30

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_alter_aboutus_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=app_users.models.logo_name, verbose_name='Logo Image')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
