# Generated by Django 3.2 on 2021-06-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Query',
        ),
    ]
