# Generated by Django 3.2 on 2021-06-01 18:19

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0085_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to=curriculum.models.save_subject_image, verbose_name='Subject Image'),
        ),
    ]
