# Generated by Django 3.2 on 2021-06-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0086_alter_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='department',
        ),
        migrations.RemoveField(
            model_name='workingdays',
            name='department',
        ),
        migrations.DeleteModel(
            name='SlotSubject',
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
        migrations.DeleteModel(
            name='WorkingDays',
        ),
    ]
