# Generated by Django 3.2.6 on 2021-08-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0087_auto_20210602_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
    ]
